server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/your-realm
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
#  datasource:
#    url: jdbc:postgresql://localhost:5432/KPO_4
#    username: postgres
#    password: 2341
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect