FROM openjdk:21

COPY TicketPurchaseOrderMicroservice/docker/TicketPurchaseOrderMicroservice.jar TicketPurchaseOrderMicroservice.jar

ENTRYPOINT ["java", "-jar", "TicketPurchaseOrderMicroservice.jar"]

EXPOSE 8082