FROM openjdk:21

COPY UserAuthenticatorMicroservice/docker/UserAuthenticatorMicroservice.jar UserAuthenticatorMicroservice.jar

ENTRYPOINT ["java", "-jar", "UserAuthenticatorMicroservice.jar"]

EXPOSE 8081